# -*- coding: utf-8 -*-
"""Decodelab_P4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TH12L0VBq6d6OlZJwzZciyCsYiYakwiX
"""

"""
=========================================================
Project 4 : Image Recognition using MobileNetV2
DecodeLabs Artificial Intelligence Internship
=========================================================
"""

import numpy as np
from tensorflow.keras.applications.mobilenet_v2 import (
    MobileNetV2,
    preprocess_input,
    decode_predictions
)
from tensorflow.keras.preprocessing import image

# --------------------------------------------
# Load Pre-trained Model
# --------------------------------------------

print("Loading MobileNetV2 Model...")

model = MobileNetV2(weights="imagenet")

print("Model Loaded Successfully!\n")

# --------------------------------------------
# Input Image
# --------------------------------------------

image_path = input("Enter image path: ")

# Load image
img = image.load_img(image_path, target_size=(224, 224))

# Convert image to array
img_array = image.img_to_array(img)

# Expand dimensions
img_array = np.expand_dims(img_array, axis=0)

# Preprocess image
img_array = preprocess_input(img_array)

# --------------------------------------------
# Prediction
# --------------------------------------------

predictions = model.predict(img_array)

results = decode_predictions(predictions, top=5)[0]

# --------------------------------------------
# Display Results
# --------------------------------------------

print("\nTop Predictions\n")
print("-" * 50)

for rank, (_, label, confidence) in enumerate(results, start=1):
    print(f"{rank}. {label}  -->  {confidence*100:.2f}%")

print("\nRecognition Completed Successfully!")